declare var OFFICE: any;
declare var OFFICE_LAYOUT: any;
declare var AVATAR_FILES: string[];
declare var SPRITE_FRAMES: Record<string, number[]>;
declare var STATE_COLORS: Record<string, string>;
declare var STATE_ZONE_MAP: Record<string, string>;
declare var IDLE_ANIM_KEYS: Set<string>;
declare var officeCoords: any;
declare var officeLayers: any;
declare var officePathfinder: any;
declare var officeSkinImages: Record<string, HTMLImageElement>;
declare var officeCharacters: any;
declare var officeRenderer: any;
declare var officeInitialized: boolean;
declare function avatarIndexFromId(id: string): number;

declare function loadAvatarFiles(): Promise<void>;
declare function loadSpriteFrames(): Promise<void>;
declare function loadOfficeLayout(): Promise<void>;
declare function loadOfficeImage(src: string): Promise<HTMLImageElement>;
declare function buildOfficeLayers(): Promise<any>;
declare function loadOfficeDecorItems(): Promise<void>;
declare function parseMapCoordinates(bgW: number, bgH: number): Promise<any>;
declare function parseObjectCoordinates(bgW: number, bgH: number): Promise<any>;
declare function loadAllOfficeSkins(): Promise<any>;
declare function getOfficeSkinImage(avatarFile: string): HTMLImageElement | undefined;
declare function drawOfficeSprite(ctx: CanvasRenderingContext2D, agent: any): void;
declare function isIdleAnim(key: string): boolean;
declare function tickOfficeAnimation(agent: any, deltaMs: number): void;
declare function animKeyFromDir(dir: string, moving: boolean): string;
declare function drawOfficeNameTag(ctx: CanvasRenderingContext2D, agent: any): void;
declare function drawOfficeBubble(ctx: CanvasRenderingContext2D, agent: any): void;
declare function getSeatConfig(id: number): any;
declare function initOffice(): Promise<void>;
declare function officeOnAgentCreated(data: any): void;
declare function officeOnAgentUpdated(data: any): void;
declare function officeOnAgentRemoved(data: { id: string }): void;
declare function stopOffice(): void;
declare function resumeOffice(): void;
